[package]
name = "server"
version = "0.1.0"
edition = "2021"
default-run = "server"

[dependencies]
axum = "0.8.1"
diesel = { version="2.2.7", features= ["mysql"] }
dotenvy = "0.15.7"
serde = { version = "1.0.217" }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
